# the service configuration in the container which will be created in the pod

apiVersion: v1
kind: Service
metadata:
  labels:
    app:  app-k8s-service # the name of the deployment service used for discovery by the K8S sluster service
  name: node-serv1-service  # the name of the service 
spec: # the service specification, The external Public port, internal port and loadbalancer
  ports:  # the external port and internal port   
    - port: 5001 # expternal port
      targetPort: 9001 # container port
  selector: # name of the POD where the container is hosting the service
    app:  node-serv1-pod
  type: LoadBalancer # allows the public communication        