# Fetch the base image from the docker hub
# fetch the ready Linux base image whihc is having
# node.js installed on it
FROM node:16-alpine3.11
# create a work directory on the Linux user path
WORKDIR /usr/src/app
# copy the package.json file on the image so that all dependencies
# will be installed
COPY package*.json ./
# inside the image run the command to install all packages
RUN npm install --only=production
# copy all the source files for executing the application in image
COPY . .
# expose the port from the container, so that the Microservice will be ready
EXPOSE 9002
# run the application
CMD [ "npm","start" ]