apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-serv2-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app:  node-serv2-pod
  template: # the POD COnfiguration
    metadata:
      labels: 
        app:  node-serv2-pod # the POD that will be created with containers in it
    spec: # define specifications for containers
      containers:
      - name: node-serv2-container # container name
        image:  mast007/b2serv2:v1 # image to be loaded in the container
        resources:  # define CPU and memory
          limits:
            cpu: "500m" # 0.5 CPU
            memory: "128Mi" # 128mb
        ports:  # ports exposed by the container
          - name: http
            containerPort:  9002    
---
# the service configuration in the container which will be created in the pod

apiVersion: v1
kind: Service
metadata:
  labels:
    app:  app-k8s2-service # the name of the deployment service used for discovery by the K8S sluster service
  name: node-serv2-service  # the name of the service 
spec: # the service specification, The external Public port, internal port and loadbalancer
  ports:  # the external port and internal port   
    - protocol: TCP
      port: 80 # expternal port
      name: http # refer the containerPort name from the deployment section
      targetPort: 9002 # container port
  selector: # name of the POD where the container is hosting the service
    app:  node-serv2-pod
  type: LoadBalancer        
                
