http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  singleserv:
    host: localhost
    paths: ['/api/emps', '/api/emps/*']
  secondserv:
    host: localhost
    paths: ['/api/pers', '/api/pers/*']    
serviceEndpoints:
   httpbin:
    url: 'https://httpbin.org'
   sigleService:
    url: 'http://localhost:9001'
   secondService:
    url: 'http://localhost:9002'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  sigleServPipeline:
    apiEndpoints:
      - singleserv
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: sigleService 
              changeOrigin: true
  secondServPipeline:
    apiEndpoints:
      - secondserv
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: secondService
              changeOrigin: true     